//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ASA.Apim.Library.CourseHeader_Service {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CourseHeader_Service", Namespace="urn:microsoft-dynamics-schemas/page/courseheader")]
    public partial class CourseHeader_Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ReadOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadByRecIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadMultipleOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsUpdatedOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRecIdFromKeyOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CourseHeader_Service() {
            this.Url = global::ASA.Apim.Library.Properties.Settings.Default.ASA_Apim_Library_CourseHeader_Service_CourseHeader_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ReadCompletedEventHandler ReadCompleted;
        
        /// <remarks/>
        public event ReadByRecIdCompletedEventHandler ReadByRecIdCompleted;
        
        /// <remarks/>
        public event ReadMultipleCompletedEventHandler ReadMultipleCompleted;
        
        /// <remarks/>
        public event IsUpdatedCompletedEventHandler IsUpdatedCompleted;
        
        /// <remarks/>
        public event GetRecIdFromKeyCompletedEventHandler GetRecIdFromKeyCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/courseheader:Read", RequestNamespace="urn:microsoft-dynamics-schemas/page/courseheader", ResponseElementName="Read_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/courseheader", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("CourseHeader")]
        public CourseHeader Read(string No) {
            object[] results = this.Invoke("Read", new object[] {
                        No});
            return ((CourseHeader)(results[0]));
        }
        
        /// <remarks/>
        public void ReadAsync(string No) {
            this.ReadAsync(No, null);
        }
        
        /// <remarks/>
        public void ReadAsync(string No, object userState) {
            if ((this.ReadOperationCompleted == null)) {
                this.ReadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadOperationCompleted);
            }
            this.InvokeAsync("Read", new object[] {
                        No}, this.ReadOperationCompleted, userState);
        }
        
        private void OnReadOperationCompleted(object arg) {
            if ((this.ReadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadCompleted(this, new ReadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/courseheader:ReadByRecId", RequestNamespace="urn:microsoft-dynamics-schemas/page/courseheader", ResponseElementName="ReadByRecId_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/courseheader", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("CourseHeader")]
        public CourseHeader ReadByRecId(string recId) {
            object[] results = this.Invoke("ReadByRecId", new object[] {
                        recId});
            return ((CourseHeader)(results[0]));
        }
        
        /// <remarks/>
        public void ReadByRecIdAsync(string recId) {
            this.ReadByRecIdAsync(recId, null);
        }
        
        /// <remarks/>
        public void ReadByRecIdAsync(string recId, object userState) {
            if ((this.ReadByRecIdOperationCompleted == null)) {
                this.ReadByRecIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadByRecIdOperationCompleted);
            }
            this.InvokeAsync("ReadByRecId", new object[] {
                        recId}, this.ReadByRecIdOperationCompleted, userState);
        }
        
        private void OnReadByRecIdOperationCompleted(object arg) {
            if ((this.ReadByRecIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadByRecIdCompleted(this, new ReadByRecIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/courseheader:ReadMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/courseheader", ResponseElementName="ReadMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/courseheader", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("ReadMultiple_Result")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public CourseHeader[] ReadMultiple([System.Xml.Serialization.XmlElementAttribute("filter")] CourseHeader_Filter[] filter, string bookmarkKey, int setSize) {
            object[] results = this.Invoke("ReadMultiple", new object[] {
                        filter,
                        bookmarkKey,
                        setSize});
            return ((CourseHeader[])(results[0]));
        }
        
        /// <remarks/>
        public void ReadMultipleAsync(CourseHeader_Filter[] filter, string bookmarkKey, int setSize) {
            this.ReadMultipleAsync(filter, bookmarkKey, setSize, null);
        }
        
        /// <remarks/>
        public void ReadMultipleAsync(CourseHeader_Filter[] filter, string bookmarkKey, int setSize, object userState) {
            if ((this.ReadMultipleOperationCompleted == null)) {
                this.ReadMultipleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadMultipleOperationCompleted);
            }
            this.InvokeAsync("ReadMultiple", new object[] {
                        filter,
                        bookmarkKey,
                        setSize}, this.ReadMultipleOperationCompleted, userState);
        }
        
        private void OnReadMultipleOperationCompleted(object arg) {
            if ((this.ReadMultipleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadMultipleCompleted(this, new ReadMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/courseheader:IsUpdated", RequestNamespace="urn:microsoft-dynamics-schemas/page/courseheader", ResponseElementName="IsUpdated_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/courseheader", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("IsUpdated_Result")]
        public bool IsUpdated(string Key) {
            object[] results = this.Invoke("IsUpdated", new object[] {
                        Key});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void IsUpdatedAsync(string Key) {
            this.IsUpdatedAsync(Key, null);
        }
        
        /// <remarks/>
        public void IsUpdatedAsync(string Key, object userState) {
            if ((this.IsUpdatedOperationCompleted == null)) {
                this.IsUpdatedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsUpdatedOperationCompleted);
            }
            this.InvokeAsync("IsUpdated", new object[] {
                        Key}, this.IsUpdatedOperationCompleted, userState);
        }
        
        private void OnIsUpdatedOperationCompleted(object arg) {
            if ((this.IsUpdatedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsUpdatedCompleted(this, new IsUpdatedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/courseheader:GetRecIdFromKey", RequestNamespace="urn:microsoft-dynamics-schemas/page/courseheader", ResponseElementName="GetRecIdFromKey_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/courseheader", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetRecIdFromKey_Result")]
        public string GetRecIdFromKey(string Key) {
            object[] results = this.Invoke("GetRecIdFromKey", new object[] {
                        Key});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetRecIdFromKeyAsync(string Key) {
            this.GetRecIdFromKeyAsync(Key, null);
        }
        
        /// <remarks/>
        public void GetRecIdFromKeyAsync(string Key, object userState) {
            if ((this.GetRecIdFromKeyOperationCompleted == null)) {
                this.GetRecIdFromKeyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRecIdFromKeyOperationCompleted);
            }
            this.InvokeAsync("GetRecIdFromKey", new object[] {
                        Key}, this.GetRecIdFromKeyOperationCompleted, userState);
        }
        
        private void OnGetRecIdFromKeyOperationCompleted(object arg) {
            if ((this.GetRecIdFromKeyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRecIdFromKeyCompleted(this, new GetRecIdFromKeyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/courseheader")]
    public partial class CourseHeader {
        
        private string keyField;
        
        private string noField;
        
        private string descriptionField;
        
        private string description_2Field;
        
        private string course_Type_NoField;
        
        private string course_Type_DescriptionField;
        
        private string course_Type_Group_CodeField;
        
        private string course_Type_Group_DescriptionField;
        
        private int max_No_ParticipantsField;
        
        private bool max_No_ParticipantsFieldSpecified;
        
        private int no_ParticipationField;
        
        private bool no_ParticipationFieldSpecified;
        
        private int no_Waiting_ListField;
        
        private bool no_Waiting_ListFieldSpecified;
        
        private System.DateTime from_DateField;
        
        private bool from_DateFieldSpecified;
        
        private System.DateTime to_DateField;
        
        private bool to_DateFieldSpecified;
        
        private System.DateTime from_TimeField;
        
        private bool from_TimeFieldSpecified;
        
        private System.DateTime to_TimeField;
        
        private bool to_TimeFieldSpecified;
        
        private int min_No_ParticipantsField;
        
        private bool min_No_ParticipantsFieldSpecified;
        
        private System.DateTime enrolment_DeadlineField;
        
        private bool enrolment_DeadlineFieldSpecified;
        
        private string course_Location_NameField;
        
        private string course_Location_AddressField;
        
        private string course_Location_Post_CodeField;
        
        private string course_Location_CityField;
        
        private string course_Location_Home_PageField;
        
        private string courseLocation_Municipal_CodeField;
        
        private string courseLocation_Municipal_NameField;
        
        private decimal courseLocation_LatitudeField;
        
        private bool courseLocation_LatitudeFieldSpecified;
        
        private decimal courseLocation_LongtitudeField;
        
        private bool courseLocation_LongtitudeFieldSpecified;
        
        private bool allow_InvoiceField;
        
        private bool allow_InvoiceFieldSpecified;
        
        private decimal qty_Meeting_TimesField;
        
        private bool qty_Meeting_TimesFieldSpecified;
        
        private string teacher_NameField;
        
        private string teacher_Work_Phone_NoField;
        
        private string teacher_Work_E_MailField;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public string No {
            get {
                return this.noField;
            }
            set {
                this.noField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Description_2 {
            get {
                return this.description_2Field;
            }
            set {
                this.description_2Field = value;
            }
        }
        
        /// <remarks/>
        public string Course_Type_No {
            get {
                return this.course_Type_NoField;
            }
            set {
                this.course_Type_NoField = value;
            }
        }
        
        /// <remarks/>
        public string Course_Type_Description {
            get {
                return this.course_Type_DescriptionField;
            }
            set {
                this.course_Type_DescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Course_Type_Group_Code {
            get {
                return this.course_Type_Group_CodeField;
            }
            set {
                this.course_Type_Group_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Course_Type_Group_Description {
            get {
                return this.course_Type_Group_DescriptionField;
            }
            set {
                this.course_Type_Group_DescriptionField = value;
            }
        }
        
        /// <remarks/>
        public int Max_No_Participants {
            get {
                return this.max_No_ParticipantsField;
            }
            set {
                this.max_No_ParticipantsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Max_No_ParticipantsSpecified {
            get {
                return this.max_No_ParticipantsFieldSpecified;
            }
            set {
                this.max_No_ParticipantsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int No_Participation {
            get {
                return this.no_ParticipationField;
            }
            set {
                this.no_ParticipationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool No_ParticipationSpecified {
            get {
                return this.no_ParticipationFieldSpecified;
            }
            set {
                this.no_ParticipationFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int No_Waiting_List {
            get {
                return this.no_Waiting_ListField;
            }
            set {
                this.no_Waiting_ListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool No_Waiting_ListSpecified {
            get {
                return this.no_Waiting_ListFieldSpecified;
            }
            set {
                this.no_Waiting_ListFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime From_Date {
            get {
                return this.from_DateField;
            }
            set {
                this.from_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool From_DateSpecified {
            get {
                return this.from_DateFieldSpecified;
            }
            set {
                this.from_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime To_Date {
            get {
                return this.to_DateField;
            }
            set {
                this.to_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool To_DateSpecified {
            get {
                return this.to_DateFieldSpecified;
            }
            set {
                this.to_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="time")]
        public System.DateTime From_Time {
            get {
                return this.from_TimeField;
            }
            set {
                this.from_TimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool From_TimeSpecified {
            get {
                return this.from_TimeFieldSpecified;
            }
            set {
                this.from_TimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="time")]
        public System.DateTime To_Time {
            get {
                return this.to_TimeField;
            }
            set {
                this.to_TimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool To_TimeSpecified {
            get {
                return this.to_TimeFieldSpecified;
            }
            set {
                this.to_TimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int Min_No_Participants {
            get {
                return this.min_No_ParticipantsField;
            }
            set {
                this.min_No_ParticipantsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Min_No_ParticipantsSpecified {
            get {
                return this.min_No_ParticipantsFieldSpecified;
            }
            set {
                this.min_No_ParticipantsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Enrolment_Deadline {
            get {
                return this.enrolment_DeadlineField;
            }
            set {
                this.enrolment_DeadlineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Enrolment_DeadlineSpecified {
            get {
                return this.enrolment_DeadlineFieldSpecified;
            }
            set {
                this.enrolment_DeadlineFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Course_Location_Name {
            get {
                return this.course_Location_NameField;
            }
            set {
                this.course_Location_NameField = value;
            }
        }
        
        /// <remarks/>
        public string Course_Location_Address {
            get {
                return this.course_Location_AddressField;
            }
            set {
                this.course_Location_AddressField = value;
            }
        }
        
        /// <remarks/>
        public string Course_Location_Post_Code {
            get {
                return this.course_Location_Post_CodeField;
            }
            set {
                this.course_Location_Post_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Course_Location_City {
            get {
                return this.course_Location_CityField;
            }
            set {
                this.course_Location_CityField = value;
            }
        }
        
        /// <remarks/>
        public string Course_Location_Home_Page {
            get {
                return this.course_Location_Home_PageField;
            }
            set {
                this.course_Location_Home_PageField = value;
            }
        }
        
        /// <remarks/>
        public string CourseLocation_Municipal_Code {
            get {
                return this.courseLocation_Municipal_CodeField;
            }
            set {
                this.courseLocation_Municipal_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string CourseLocation_Municipal_Name {
            get {
                return this.courseLocation_Municipal_NameField;
            }
            set {
                this.courseLocation_Municipal_NameField = value;
            }
        }
        
        /// <remarks/>
        public decimal CourseLocation_Latitude {
            get {
                return this.courseLocation_LatitudeField;
            }
            set {
                this.courseLocation_LatitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CourseLocation_LatitudeSpecified {
            get {
                return this.courseLocation_LatitudeFieldSpecified;
            }
            set {
                this.courseLocation_LatitudeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal CourseLocation_Longtitude {
            get {
                return this.courseLocation_LongtitudeField;
            }
            set {
                this.courseLocation_LongtitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CourseLocation_LongtitudeSpecified {
            get {
                return this.courseLocation_LongtitudeFieldSpecified;
            }
            set {
                this.courseLocation_LongtitudeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool Allow_Invoice {
            get {
                return this.allow_InvoiceField;
            }
            set {
                this.allow_InvoiceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Allow_InvoiceSpecified {
            get {
                return this.allow_InvoiceFieldSpecified;
            }
            set {
                this.allow_InvoiceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Qty_Meeting_Times {
            get {
                return this.qty_Meeting_TimesField;
            }
            set {
                this.qty_Meeting_TimesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Qty_Meeting_TimesSpecified {
            get {
                return this.qty_Meeting_TimesFieldSpecified;
            }
            set {
                this.qty_Meeting_TimesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Teacher_Name {
            get {
                return this.teacher_NameField;
            }
            set {
                this.teacher_NameField = value;
            }
        }
        
        /// <remarks/>
        public string Teacher_Work_Phone_No {
            get {
                return this.teacher_Work_Phone_NoField;
            }
            set {
                this.teacher_Work_Phone_NoField = value;
            }
        }
        
        /// <remarks/>
        public string Teacher_Work_E_Mail {
            get {
                return this.teacher_Work_E_MailField;
            }
            set {
                this.teacher_Work_E_MailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/courseheader")]
    public partial class CourseHeader_Filter {
        
        private CourseHeader_Fields fieldField;
        
        private string criteriaField;
        
        /// <remarks/>
        public CourseHeader_Fields Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        public string Criteria {
            get {
                return this.criteriaField;
            }
            set {
                this.criteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/courseheader")]
    public enum CourseHeader_Fields {
        
        /// <remarks/>
        No,
        
        /// <remarks/>
        Description,
        
        /// <remarks/>
        Description_2,
        
        /// <remarks/>
        Course_Type_No,
        
        /// <remarks/>
        Course_Type_Description,
        
        /// <remarks/>
        Course_Type_Group_Code,
        
        /// <remarks/>
        Course_Type_Group_Description,
        
        /// <remarks/>
        Max_No_Participants,
        
        /// <remarks/>
        No_Participation,
        
        /// <remarks/>
        No_Waiting_List,
        
        /// <remarks/>
        From_Date,
        
        /// <remarks/>
        To_Date,
        
        /// <remarks/>
        From_Time,
        
        /// <remarks/>
        To_Time,
        
        /// <remarks/>
        Min_No_Participants,
        
        /// <remarks/>
        Enrolment_Deadline,
        
        /// <remarks/>
        Course_Location_Name,
        
        /// <remarks/>
        Course_Location_Address,
        
        /// <remarks/>
        Course_Location_Post_Code,
        
        /// <remarks/>
        Course_Location_City,
        
        /// <remarks/>
        Course_Location_Home_Page,
        
        /// <remarks/>
        CourseLocation_Municipal_Code,
        
        /// <remarks/>
        CourseLocation_Municipal_Name,
        
        /// <remarks/>
        CourseLocation_Latitude,
        
        /// <remarks/>
        CourseLocation_Longtitude,
        
        /// <remarks/>
        Allow_Invoice,
        
        /// <remarks/>
        Qty_Meeting_Times,
        
        /// <remarks/>
        Teacher_Name,
        
        /// <remarks/>
        Teacher_Work_Phone_No,
        
        /// <remarks/>
        Teacher_Work_E_Mail,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void ReadCompletedEventHandler(object sender, ReadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CourseHeader Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CourseHeader)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void ReadByRecIdCompletedEventHandler(object sender, ReadByRecIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadByRecIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadByRecIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CourseHeader Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CourseHeader)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void ReadMultipleCompletedEventHandler(object sender, ReadMultipleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadMultipleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadMultipleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CourseHeader[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CourseHeader[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void IsUpdatedCompletedEventHandler(object sender, IsUpdatedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsUpdatedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsUpdatedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetRecIdFromKeyCompletedEventHandler(object sender, GetRecIdFromKeyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRecIdFromKeyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRecIdFromKeyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591