//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASA.Apim.Library.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://consulthidanapi.azure-api.net/nav/courseheader")]
        public string ASA_Apim_Library_CourseHeader_Service_CourseHeader_Service {
            get {
                return ((string)(this["ASA_Apim_Library_CourseHeader_Service_CourseHeader_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://consulthidanapi.azure-api.net/nav/countries")]
        public string ASA_Apim_Library_Countries_Service_Countries_Service {
            get {
                return ((string)(this["ASA_Apim_Library_Countries_Service_Countries_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://consulthidanapi.azure-api.net/nav/courselist")]
        public string ASA_Apim_Library_CourseList_Service_CourseList_Service {
            get {
                return ((string)(this["ASA_Apim_Library_CourseList_Service_CourseList_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://consulthidanapi.azure-api.net/nav/courseprices")]
        public string ASA_Apim_Library_CoursePrices_Service_CoursePrices_Service {
            get {
                return ((string)(this["ASA_Apim_Library_CoursePrices_Service_CoursePrices_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://consulthidanapi.azure-api.net/nav/honoraryoffices")]
        public string ASA_Apim_Library_HonoraryOffices_Service_HonoraryOffices_Service {
            get {
                return ((string)(this["ASA_Apim_Library_HonoraryOffices_Service_HonoraryOffices_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://consulthidanapi.azure-api.net/nav/postcodes")]
        public string ASA_Apim_Library_PostCodes_Service_PostCodes_Service {
            get {
                return ((string)(this["ASA_Apim_Library_PostCodes_Service_PostCodes_Service"]));
            }
        }
    }
}
