//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ASA.Apim.Library.CourseEnrollments_Service {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CourseEnrollments", Namespace="urn:microsoft-dynamics-schemas/codeunit/CourseEnrollments")]
    public partial class CourseEnrollments : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CallCourseEnrollmentsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CourseEnrollments() {
            this.Url = global::ASA.Apim.Library.Properties.Settings.Default.ASA_Apim_Library_CourseEnrollments_Service_CourseEnrollments;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CallCourseEnrollmentsCompletedEventHandler CallCourseEnrollmentsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/CourseEnrollments:CourseEnrollments", RequestElementName="CourseEnrollments", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/CourseEnrollments", ResponseElementName="CourseEnrollments_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/CourseEnrollments", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CallCourseEnrollments(ref CourseEnrollments1 courseEnrollXML) {
            object[] results = this.Invoke("CallCourseEnrollments", new object[] {
                        courseEnrollXML});
            courseEnrollXML = ((CourseEnrollments1)(results[0]));
        }
        
        /// <remarks/>
        public void CallCourseEnrollmentsAsync(CourseEnrollments1 courseEnrollXML) {
            this.CallCourseEnrollmentsAsync(courseEnrollXML, null);
        }
        
        /// <remarks/>
        public void CallCourseEnrollmentsAsync(CourseEnrollments1 courseEnrollXML, object userState) {
            if ((this.CallCourseEnrollmentsOperationCompleted == null)) {
                this.CallCourseEnrollmentsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCallCourseEnrollmentsOperationCompleted);
            }
            this.InvokeAsync("CallCourseEnrollments", new object[] {
                        courseEnrollXML}, this.CallCourseEnrollmentsOperationCompleted, userState);
        }
        
        private void OnCallCourseEnrollmentsOperationCompleted(object arg) {
            if ((this.CallCourseEnrollmentsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CallCourseEnrollmentsCompleted(this, new CallCourseEnrollmentsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="CourseEnrollments", Namespace="urn:microsoft-dynamics-nav/xmlports/x6148513")]
    public partial class CourseEnrollments1 {
        
        private CourseEnrollment[] courseEnrollmentField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CourseEnrollment")]
        public CourseEnrollment[] CourseEnrollment {
            get {
                return this.courseEnrollmentField;
            }
            set {
                this.courseEnrollmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/x6148513")]
    public partial class CourseEnrollment {
        
        private string participantNoField;
        
        private int participantEntryNoField;
        
        private string customerNoField;
        
        private string courseNoField;
        
        private decimal priceField;
        
        private string wayOfPaymentField;
        
        private string paymentReferenceField;
        
        private decimal paidAmountField;
        
        private string nameField;
        
        private string name2Field;
        
        private string addressField;
        
        private string streetNameField;
        
        private int streetNoField;
        
        private string streetNoExtensionField;
        
        private string floorNoField;
        
        private string floorNoExtensionField;
        
        private int postBoxField;
        
        private string address2Field;
        
        private string postCodeField;
        
        private string cityField;
        
        private string countryCodeField;
        
        private string phoneNoField;
        
        private string workPhoneNoField;
        
        private string mobilePhoneNoField;
        
        private string emailField;
        
        private string socialSecurityNoField;
        
        private string participantTypeField;
        
        private string participantBillToField;
        
        private string eANnoField;
        
        private string portalOrderIdField;
        
        public CourseEnrollment() {
            this.participantEntryNoField = 0;
            this.priceField = ((decimal)(0m));
            this.paidAmountField = ((decimal)(0m));
            this.streetNoField = 0;
            this.postBoxField = 0;
        }
        
        /// <remarks/>
        public string ParticipantNo {
            get {
                return this.participantNoField;
            }
            set {
                this.participantNoField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int ParticipantEntryNo {
            get {
                return this.participantEntryNoField;
            }
            set {
                this.participantEntryNoField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerNo {
            get {
                return this.customerNoField;
            }
            set {
                this.customerNoField = value;
            }
        }
        
        /// <remarks/>
        public string CourseNo {
            get {
                return this.courseNoField;
            }
            set {
                this.courseNoField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "0")]
        public decimal Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        public string WayOfPayment {
            get {
                return this.wayOfPaymentField;
            }
            set {
                this.wayOfPaymentField = value;
            }
        }
        
        /// <remarks/>
        public string PaymentReference {
            get {
                return this.paymentReferenceField;
            }
            set {
                this.paymentReferenceField = value;
            }
        }
        
        /// <remarks/>
        public decimal PaidAmount {
            get {
                return this.paidAmountField;
            }
            set {
                this.paidAmountField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Name2 {
            get {
                return this.name2Field;
            }
            set {
                this.name2Field = value;
            }
        }
        
        /// <remarks/>
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public string StreetName {
            get {
                return this.streetNameField;
            }
            set {
                this.streetNameField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int StreetNo {
            get {
                return this.streetNoField;
            }
            set {
                this.streetNoField = value;
            }
        }
        
        /// <remarks/>
        public string StreetNoExtension {
            get {
                return this.streetNoExtensionField;
            }
            set {
                this.streetNoExtensionField = value;
            }
        }
        
        /// <remarks/>
        public string FloorNo {
            get {
                return this.floorNoField;
            }
            set {
                this.floorNoField = value;
            }
        }
        
        /// <remarks/>
        public string FloorNoExtension {
            get {
                return this.floorNoExtensionField;
            }
            set {
                this.floorNoExtensionField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int PostBox {
            get {
                return this.postBoxField;
            }
            set {
                this.postBoxField = value;
            }
        }
        
        /// <remarks/>
        public string Address2 {
            get {
                return this.address2Field;
            }
            set {
                this.address2Field = value;
            }
        }
        
        /// <remarks/>
        public string PostCode {
            get {
                return this.postCodeField;
            }
            set {
                this.postCodeField = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string CountryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
            }
        }
        
        /// <remarks/>
        public string PhoneNo {
            get {
                return this.phoneNoField;
            }
            set {
                this.phoneNoField = value;
            }
        }
        
        /// <remarks/>
        public string WorkPhoneNo {
            get {
                return this.workPhoneNoField;
            }
            set {
                this.workPhoneNoField = value;
            }
        }
        
        /// <remarks/>
        public string MobilePhoneNo {
            get {
                return this.mobilePhoneNoField;
            }
            set {
                this.mobilePhoneNoField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string SocialSecurityNo {
            get {
                return this.socialSecurityNoField;
            }
            set {
                this.socialSecurityNoField = value;
            }
        }
        
        /// <remarks/>
        public string ParticipantType {
            get {
                return this.participantTypeField;
            }
            set {
                this.participantTypeField = value;
            }
        }
        
        /// <remarks/>
        public string ParticipantBillTo {
            get {
                return this.participantBillToField;
            }
            set {
                this.participantBillToField = value;
            }
        }
        
        /// <remarks/>
        public string EANno {
            get {
                return this.eANnoField;
            }
            set {
                this.eANnoField = value;
            }
        }
        
        /// <remarks/>
        public string PortalOrderId {
            get {
                return this.portalOrderIdField;
            }
            set {
                this.portalOrderIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void CallCourseEnrollmentsCompletedEventHandler(object sender, CallCourseEnrollmentsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CallCourseEnrollmentsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CallCourseEnrollmentsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CourseEnrollments1 courseEnrollXML {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CourseEnrollments1)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591